version: "3.9"
services:
  pupper_pals_db:
    image: postgres
    ports:
      - "1200:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  pupper_pals_app:
    image: pupperpals:dev
    ports:
      - "1000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dockercompose
    depends_on:
      - pupper_pals_db
